vich_uploader:
  db_driver: orm

  mappings:
    outfit_file:
      uri_prefix: /uploads/outfit
      upload_destination: '%kernel.project_dir%/public/outfit/'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer